# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationTask',
            fields=[
                ('task_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('no_sequences', models.PositiveIntegerField(default=0)),
                ('downstream_protein_task_id', models.CharField(max_length=256)),
            ],
        ),
    ]
