# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512, null=True)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HydrogenaseClass',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('putative_class', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=512)),
                ('subgroup', models.CharField(max_length=512)),
                ('function', models.TextField()),
                ('activity', models.CharField(max_length=512)),
                ('oxygen_tolerance', models.CharField(max_length=512)),
                ('localisation', models.CharField(max_length=512)),
                ('ecosystem_distribution', models.CharField(max_length=512)),
                ('taxonomic_distribution', models.CharField(max_length=512)),
                ('distribution_image', models.FileField(null=True, upload_to='')),
                ('subunits', models.CharField(max_length=128)),
                ('subunit_description', models.TextField(blank=True, default='')),
                ('catalytic_site', models.CharField(max_length=512)),
                ('fes_clusters', models.TextField(blank=True, default='', max_length=512)),
                ('accessory_subunits', models.CharField(max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('literature', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Hydrogenase classes',
            },
        ),
        migrations.CreateModel(
            name='HydrogenaseSequence',
            fields=[
                ('ncbi_accession', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='NCBI accession')),
                ('organism', models.CharField(max_length=256, verbose_name='Organism')),
                ('hydrogenase', models.CharField(max_length=256, verbose_name='Hydrogenase')),
                ('protein_sequence', models.TextField(verbose_name='Protein Sequence')),
                ('phylum', models.CharField(max_length=256, verbose_name='Phylum')),
                ('order', models.CharField(max_length=256, verbose_name='Order')),
                ('activity_predicted', models.CharField(choices=[('Bidirectional', 'Bidirectional'), ('Evolving', 'Evolving'), ('Bifurcating', 'Bifurcating'), ('Sensory', 'Sensory'), ('Anaerobic Uptake', 'Anaerobic Uptake'), ('Aerobic Uptake', 'Aerobic Uptake')], max_length=25, verbose_name='Activity (Predicted)')),
                ('oxygen_tolerance_predicted', models.CharField(choices=[('Tolerant', 'Tolerant'), ('Labile', 'Labile'), ('Sensitive', 'Sensitive'), ('Unknown', 'Unknown')], max_length=25, verbose_name='Oxygen Tolerance (Predicted)')),
                ('subunits_predicted', models.CharField(max_length=256, verbose_name='Subunits (Predicted)')),
                ('metal_centres_predicted', models.CharField(max_length=256, verbose_name='Metal Centres (Predicted)')),
                ('accessory_subunits_predicted', models.CharField(max_length=256, verbose_name='Accessory Subunits (Predicted)')),
            ],
        ),
        migrations.CreateModel(
            name='NonHydrogenaseSequence',
            fields=[
                ('organism', models.CharField(max_length=256, verbose_name='Organism')),
                ('accession', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='NCBI accession')),
                ('protein_sequence', models.TextField(verbose_name='Protein Sequence')),
                ('phylum', models.CharField(max_length=256, verbose_name='Phylum')),
                ('order', models.CharField(max_length=256, verbose_name='Order')),
                ('domain', models.CharField(max_length=256, verbose_name='Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=256)),
                ('hydrogenase_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.HydrogenaseClass')),
            ],
        ),
        migrations.AddField(
            model_name='geneticorganisation',
            name='hydrogenase_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.HydrogenaseClass'),
        ),
    ]
