# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogenaseclass',
            name='accessory_subunits',
        ),
    ]
