# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_remove_hydrogenaseclass_accessory_subunits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrogenaseclass',
            options={'ordering': ['name'], 'verbose_name_plural': 'Hydrogenase classes'},
        ),
        migrations.AddField(
            model_name='hydrogenasesequence',
            name='hydrogenase_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.HydrogenaseClass'),
        ),
    ]
