# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 14:08
from __future__ import unicode_literals

from django.db import migrations


def set_hydrogenase_foreign_key(apps, schema_editor):
    HydrogenaseSequence = apps.get_model('browser', 'HydrogenaseSequence')
    HydrogenaseClass = apps.get_model('browser', 'HydrogenaseClass')

    for seq in HydrogenaseSequence.objects.all():
        hydrogenase_class = HydrogenaseClass.objects.get(pk=seq.hydrogenase)
        seq.hydrogenase_class = hydrogenase_class
        seq.save()


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20160607_1407'),
    ]

    operations = [
        migrations.RunPython(set_hydrogenase_foreign_key),
    ]
