# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20160607_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrogenasesequence',
            name='hydrogenase',
        ),
    ]
