# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_auto_20160726_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrogenasesequence',
            name='sequence_for_classification',
            field=models.TextField(blank=True, help_text="Protein sequence used for classification. This will not be shown in the Browser. If this sequence is not provided the 'Protein Sequence' will be used instead.", verbose_name='Sequence for Classification'),
        ),
        migrations.AlterField(
            model_name='hydrogenaseclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hydrogenasesequence',
            name='protein_sequence',
            field=models.TextField(help_text='Protein sequence for the hydrogenase. This will be shown in the Browser.', verbose_name='Protein Sequence'),
        ),
    ]
