# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_add_hydrogenaseclass_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrogenaseclass',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
