# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_auto_20160805_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrogenasesequence',
            name='dna_sequence',
            field=models.TextField(help_text='DNA sequence for the hydrogenase.', null=True, verbose_name='DNA Sequence'),
        ),
    ]
