# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_hydrogenasesequence_dna_sequence'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='hydrogenasesequence',
            index_together=set([('hydrogenase_class',)]),
        ),
    ]
