# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_auto_20160808_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrogenasesequence',
            name='dna_sequence',
            field=models.TextField(blank=True, default='', help_text='DNA sequence for the hydrogenase.', null=True, verbose_name='DNA Sequence'),
        ),
    ]
